### ISSUE TITLE
Output file requirements

### ISSUE THREAD

**Issue by mjsonofharry** [ContentsMayBeHot/RivalsofAetherReplayParser#3]
For each frame, a list of keys that are being pressed during that frame. e.g.:

```
...
234 ATTACK DOWN
235 ATTACK DOWN
236 ATTACK
...
```

Note the lack of _PRESSED or _RELEASED or similar descriptions. Instead of strings they could be enums, but we'll need a different ActionType enum that doesn't distinguish between pressed/released states.

**Comment by mjsonofharry** [comment]
It could also take the format of a 2D matrix. Each row is a frame and each column is an action type. This would actually be preferable.

**Comment by mjsonofharry** [comment]
Yes please do the matrix.

**Comment by sensdoggo** [comment]
added in 837f515a17b122171e5e40084b4683317a74fd84
